STR-43 -- Modified Dockerfile, docker-compose.yml, and laravel-echo
csuntechlab/iSTART pull request #14
Opened 2019-03-01 23:30 UTC by ebm17915

# Description
'Write a meaningful description of your task'
  
# Testing
'What does the reviewer need to do to test your PR?'

# Installation
'Are there any dependencies the reviewer needs to download?'

2019-03-06 23:16 UTC, digitalsoba commented on Dockerfile
> +COPY --from=dev /var/www/html /var/www/html
There is no layer called `dev`

2019-03-06 23:17 UTC, digitalsoba requested changes
Make the quick change, can't test out Laravel echo but everything else is 👍

2019-03-16 00:46 UTC, ruizjorgealt commented
Not accessible through localhost

2019-03-18 22:43 UTC, digitalsoba commented on Dockerfile
> +RUN \
Separate Redis into another container in `docker-compose.yml`

2019-03-18 22:52 UTC, digitalsoba submitted a review, later dismissed
Step 11/22 `Error: ENOENT: no such file or directory, open '/public/css/app.css'` in the build process where `yarn install && yarn run prod`

2019-03-20 18:19 UTC, luisjg requested changes
It's missing the php-ldap extension

2019-03-20 19:02 UTC, luisjg approved these changes
👍

2019-03-20 19:28 UTC, ruizjorgealt commented
Looks good to me!

2019-03-20 19:29 UTC, ruizjorgealt approved these changes
Works fine!

2019-03-20 19:31 UTC, merged