STR-49 -- FE: FE: Verify a users session inactivity
csuntechlab/iSTART pull request #31
Opened 2019-03-18 23:14 UTC by ekno27

# Description
'Automatically logs out user after 27 minutes of inactivity per CSUN's standard'
  
# Testing
1. add the .env variable i sent in my email to your .env file
2. change the variable's value to something like .125 (.125 = ~7 seconds after conversion)
2. login
3. Do nothing in the window: do not move mouse, touch keyboard, scroll wheel, etc.
4. wait
5. You should be logged out after the time specified in the env value

2019-03-18 23:27 UTC, liadGolan submitted a review, later dismissed
👍

2019-03-18 23:45 UTC, frlzjosh requested changes
Unable to logout from the navbar component

2019-03-19 00:16 UTC, frlzjosh commented on resources/js/App.vue
> +        console.log('logout')
do we still need the console.log ?

2019-03-19 00:18 UTC, frlzjosh requested changes
One some request

2019-03-19 00:24 UTC, frlzjosh commented on resources/js/App.vue
>          }
you chose the wrong path when fixing merge conflicts

2019-03-19 00:25 UTC, frlzjosh requested changes
one small lil change

2019-03-19 00:51 UTC, frlzjosh approved these changes
Is goood

2019-03-19 16:32 UTC, liadGolan requested changes
Log out does not reflect until I move my mouse after the timeout. Also the .env change needs to be reflected in .env.example

2019-03-19 16:51 UTC, liadGolan approved these changes

2019-03-19 18:08 UTC, andrewMETALAB approved these changes
👍

2019-03-19 18:08 UTC, merged