STR-54 -- FE: Create the admin page with the ability to take in an excel sheet and pass it to the backend
csuntechlab/iSTART pull request #42
Opened 2019-03-28 17:41 UTC by ekno27

# Description
Allows admin to upload an excel sheet that parses through the file and will send the sheet's contents to the backend.
  
# Testing
1. Upload a file that isnt excel (pdf, word, mp3, etc), you should be notified to use an excel file
2. upload the excel file that was sent by me on the iSTART slack channel 
3. to check the parsed file, check the admin component using vue devtools

## NOTE: Pressing the submit button will give you a 404 POST  error, this is because the route this is posting to does not exist yet, the route will be created on STR-55.  

# Installation
Sheets.js's xlsx was used in order to parse through the file. To install, just ``yarn add``

2019-03-28 17:58 UTC, BrianLinggadjaja submitted a review, later dismissed
Everything else is good including test, I just noticed that some extensions don't put out a message such as ***`(.pdf, .exe, etc.)`***

2019-03-29 21:11 UTC, frlzjosh commented on resources/js/views/admin.vue
> +    handleFileChange(evt) {
change `evt` to something like `fileEvent`

2019-03-29 21:13 UTC, frlzjosh commented on tests/jsUnit/views/admin.spec.js
> +    mocks: {$route}
nice!

2019-03-29 21:14 UTC, frlzjosh requested changes
very small changes needed.

2019-03-29 21:23 UTC, frlzjosh approved these changes
wow edgar! L0okS gR3At

2019-04-02 19:04 UTC, andrewMETALAB requested changes
In your instructions, you said: "to check the parsed file, check the admin component using vue devtools".
But I don't see any difference in the vue dev tools after uploading your excel file and clicking "submit", so I'm a little confused.
Come show me what I should be seeing next time you're in? Thank you sir.

2019-04-03 16:28 UTC, andrewMETALAB approved these changes

2019-04-03 16:28 UTC, merged