STR-71 -- FE: Hamburger Menu does not fill up all the way at once
csuntechlab/iSTART pull request #43
Opened 2019-03-28 19:43 UTC by BrianLinggadjaja

# Description
Added event to toggle a new dropdown navigation.
  
# Testing
1. Login as any user ***`example: cyndee.bellamy`*** .
2. Ensure the top navigation bar is properly aligned to content.
3. Click the navigation button and ensure the dropdown functionality works.
4. Make sure everything looks good and has no weird visual bugs.
5. Ensure the visual quality at different viewports.

2019-03-29 18:56 UTC, frlzjosh submitted a review, later dismissed
Code is good, and the navbar looks great, except there a few things:
1. When clicking on a selection on the navbar, it does not close. You need to add an event that will also close the navbar when selection a field inside of the navbar.
2. The 404 error page does not redirect to the dashboard. (Might have been done in your branch, so sorry if it wasn't your fault)

2019-03-29 22:24 UTC, mbendandour reviewed
The images don't load for the modules on my desktop, I'm using MAMP
Also, I'm not sure what you mean by the hamburger menu is aligned properly with the modules, but from my end, the modules are about an inch to the right of the hamburger menu. I like how it looks this way though!

2019-04-02 18:38 UTC, andrewMETALAB requested changes
(1) see inline comment about padding
(2) a `<ul>` tag's direct children can only be `<li>` tags. Currently you are breaking this rule. Feel free to fix the structure OR remove the `<ul>` and `<li>s` entirely, replacing them with `<div>s`.
(3) The navigation links need to be inside the `<nav>` tag
(4) You're breaking BEM convention with classes like `navbar__dropdown-divider` and `navbar__dropdown-item`. Hint: I think `navbar__dropdown` should be updated to be `navbar-dropdown` so that it's a block instead of an element.

2019-04-02 18:38 UTC, andrewMETALAB commented on resources/sass/global/_navbar.scss
> +            padding: 0.5rem;
Please change this to `padding: 0.5rem 0` in order to prevent the nav items from moving to the right/left slightly as the menu opens/closes.

2019-04-03 16:33 UTC, andrewMETALAB approved these changes

2019-04-03 19:49 UTC, frlzjosh reviewed
it works great man!

2019-04-03 19:49 UTC, frlzjosh approved these changes
Great job man!

2019-04-03 19:51 UTC, merged