STR-25--BE: Send and email to the "Client" when a student completes a module
csuntechlab/iSTART pull request #44
Opened 2019-03-29 21:45 UTC by mbendandour

# Description
Sends an email to admin when module of a user is complete  
# Testing
For specific research id and module name, log in as Matt first.
 Depending on your .env file, if you are using **log** then check your storage/log for the admin email. Else, check whatever designated email you put under RECEIVE_EMAIL
# Installation
'Are there any dependencies the reviewer needs to download?'
no

2019-03-29 22:37 UTC, liadGolan requested changes
Besides this small change it looks good

2019-03-29 22:37 UTC, liadGolan commented on routes/web.php
> +Route::get('/sendMailTest','UserCompletesModuleEmailController@sendMail');
I think a separate route for testing emails makes more sense here

2019-03-29 22:39 UTC, liadGolan requested changes
Attempting to send a test email results in a laravel error

2019-03-29 23:46 UTC, liadGolan approved these changes
👍

2019-04-03 22:20 UTC, nercesk approved these changes

2019-04-03 22:20 UTC, merged