STR-60 -- FE - Create alcohol module thumbnail
csuntechlab/iSTART pull request #48
Opened 2019-04-03 23:54 UTC by frlzjosh

# Description
'Write a meaningful description of your task'
  Create the alcohol module thumbnail
# Testing
'What does the reviewer need to do to test your PR?'
 1. Make sure to login as someone with module thumbail. I've been using `april.feldman`
 2. Look at my code make sure it's good, & give help/critique
 3. Make sure it is mobile responsive and pleasing to the eye
 4. Make sure it is close to the mockup. 
# Installation
'Are there any dependencies the reviewer needs to download?'
If you do not see the progress bar loading, then you will need to run `yarn install`

2019-04-05 17:17 UTC, mbendandour reviewed
The photos don't work on my MAMP machine, but the days and completion shows up and looks nice

2019-04-05 21:41 UTC, andrewMETALAB requested changes
Overall this is great work. 

You broke BEM convention just a little, but it should be pretty easy to fix...
`dashboard-module__body` is an element (which is legit), but then you have other _"elements of that element"_ such as `dashboard-module__body-progress` and `dashboard-module__body-text`. You aren't supposed to have _"elements of elements"_ like that. So instead of naming them like that, they should all just be elements of `dashboard-module` So basically update them to  `dashboard-module__progress` and `dashboard-module__text` and so on. 

Ok now for your padding and margin helper classes! I actually think this is pretty cool and could be helpful. But I think we should use `rems` instead of `px` values. Also do you think we are "stepping on the toes" of bootstrap by creating these, since bootstrap offers something similar? Maybe we should keep the naming consistent with bootrap's classes? Read this and let me know what you think: https://getbootstrap.com/docs/4.3/utilities/spacing/

2019-04-05 21:41 UTC, andrewMETALAB commented on resources/js/components/dashboard/DashboardModule.vue
> +                 :class="item.completion.progress.toString().length <= 2 ?
cool inline ternary statement!  and perfect usage of BEM modifier!

2019-04-08 23:51 UTC, andrewMETALAB approved these changes
Very well done 👍 👍 👍

2019-04-10 18:33 UTC, BrianLinggadjaja approved these changes
Awesome!

2019-04-10 18:34 UTC, merged