BE: Make middleware on backend router
csuntechlab/iSTART pull request #49
Opened 2019-04-05 16:47 UTC by mbendandour

# Description
I added code to the Handler.php that would route a user to a 404 blade if they typed in a route that doesn't exist. Moreover, if they are logged in and type in a route that doesn't exist, they should get routed back to the login page  
# Testing
Remove the # in the url and type in '/helloo' in the route. You should see a 404. Next, log in as steve. Remove the #, and type in any non-existent url, like '/blah'. This should take you back to the login page
# Installation
no

2019-04-08 16:25 UTC, liadGolan requested changes
Middleware should not log a person a out if they go outside the view app, if they are still detected as logged in, they should be directed to the application.

If someone is not logged in, they should be redirected to the front end page rather than being given a JSON with 404

2019-04-08 22:01 UTC, liadGolan approved these changes
👍

2019-04-19 22:34 UTC, luisjg requested changes
See comments

2019-04-19 22:34 UTC, luisjg commented on app/Http/Kernel.php
> +//            \Illuminate\Session\Middleware\StartSession::class,
We should remove it from this list

2019-04-29 20:57 UTC, luisjg approved these changes
👍

2019-04-29 22:10 UTC, merged