STR-88--BE: Upload "good" research json to the participant_id table
csuntechlab/iSTART pull request #54
Opened 2019-04-12 18:33 UTC by mbendandour

# Description
Adds participants labelled 'good' to the db  
# Testing
**Using Postman:**
add this to the body:
{"good":[{"email":"nr_liad.golan.736@my.csun.edu","participant_id":689679,"user_id":"members:106771546"},{"email":"nr_brian.linggadjaja.785@my.csun.edu","participant_id":41210,"user_id":"members:108688604"},{"email":"nr_joshua.magdaleno.472@my.csun.edu","participant_id":5784,"user_id":"members:107046340"},{"email":"nr_mbenda.ndour.487@my.csun.edu","participant_id":11137,"user_id":"members:103338987"},{"email":"nr_edgar.canozelaya.6@my.csun.edu","participant_id":43466,"user_id":"members:108687187"}],"bad":[{"email":"nr_yeslawd@aol.com","participant_id":3849894},{"email":"nr_imavirus@donottrustme.com","participant_id":0}]}
-Under the Header tab, put Content-Type for **Key** and application/json; charset=UTF-8 for **value**
Make sure you are using a Post request and calling route '/sendGoodParticipants'.
Hit send. 
Check your db. Creds should be in the participants table
# Installation
'Are there any dependencies the reviewer needs to download?'

2019-04-12 22:23 UTC, frlzjosh approved these changes
good!

2019-04-19 22:57 UTC, luisjg requested changes
See comments

2019-04-19 22:57 UTC, luisjg commented on app/Models/User.php
> +    public function Participant(){
This does not follow `PSR-2` standard

2019-04-19 22:57 UTC, luisjg commented on app/Services/AuthenticationService.php
> +    protected $ParticipantUtility = null;
This does not follow `PSR-2` standard

2019-04-19 22:57 UTC, luisjg commented on app/Services/UserAssignedGroupEmailService.php
> +        $ParticipantID = Participant::find($user['user_id']);
This does not follow `PSR-2` standard

2019-04-19 22:57 UTC, luisjg commented on app/Services/UserCompletesModuleEmailService.php
> +        $ParticipantID = Participant::find($user['user_id']);
This does not follow `PSR-2` standard

2019-04-22 21:03 UTC, luisjg approved these changes
👍

2019-04-22 21:23 UTC, merged