STR-101 -- FE: Make dashboard page mobile responsive
csuntechlab/iSTART pull request #64
Opened 2019-04-24 19:30 UTC by BrianLinggadjaja

# Description
Made desktop version responsive; added specific alt-text depending on substance.
  
# Testing
1. Login as `cyndee.bellamy` or `april.feldman`.
2. View the mobile and desktop viewports and ensure everything scales properly.
3. Check to see if there is any overflows, positioning of elements.
4. Ensure it meets the format of the desktop mock-up.

2019-04-24 21:30 UTC, andrewMETALAB requested changes
Looking really good. The only funkyness I see is:

(1) Some funkyness with the thumbnail images, but I'm not going to worry about it for now, since these are not the final images. Once we have the final images, let's make sure that we resize them in photoshop so that they aren't unnecessarily large. 
(2) Looks like the navbar extends beyond the rest of the content on both sides. Can we fix this please?

2019-04-24 21:34 UTC, andrewMETALAB approved these changes

2019-04-24 23:16 UTC, frlzjosh commented on resources/js/components/dashboard/DashboardModule.vue
> +                  <span class="dashboard-module__date ml-3">{{ item.completion.date}}</span>
based on the mockup it seems like you can add a `mt-1` class in this div to add some margin to the text that goes under here

2019-04-24 23:22 UTC, frlzjosh submitted a review, later dismissed
Very minor things:
1 ) The buttons are a bit smaller on the mock up
2 ) The photos have a `border-radius` on the mock up for desktop version
3 ) The titles for the modules are bold on desktop
4 ) For some reason the font awesome icons went away

2019-04-25 18:27 UTC, BrianLinggadjaja commented
> Very minor things:
> 1 ) The buttons are a bit smaller on the mock up
> 2 ) The photos have a `border-radius` on the mock up for desktop version
> 3 ) The titles for the modules are bold on desktop
> 4 ) For some reason the font awesome icons went away

1. I followed the font-size from the mock-up which was 20px and scaled it doing 20/16 into rem.
2. The updated desktop mock-up doesn't have rounded edges I believe.
3. Font-weight bold wasn't supported in our current font so I just made it Arial in the header.
4. Fixed the font-awesome on desktop.

2019-04-26 16:38 UTC, frlzjosh commented on resources/js/components/dashboard/DashboardModule.vue
> +          altText: 'alcohol substance',
deng that's hard

2019-04-26 16:59 UTC, frlzjosh approved these changes
you riiight!

2019-04-26 17:44 UTC, merged