STR-24--BE: Keep track of when a new module is available for a user
csuntechlab/iSTART pull request #67
Opened 2019-04-26 23:32 UTC by mbendandour

# Description
Sends an email at a specific time when a new module available
  
# Testing
Run "php artisan queue:listen --tries=1"
Open another terminal window and Run "redis-server"
Go to postman and send a user_id in the body to the route "/newModuleAvailable"
Look at the terminal window where you ran the queue command. When you hit send on postman, there should be a 5 second delay before you see anything on the terminal

Check to see if an email was sent to you if 'smtp' is in your env files, or check your log if your email is set up to go to log

# Installation
'Are there any dependencies the reviewer needs to download?'

2019-04-29 18:39 UTC, luisjg submitted a review, later dismissed
See comment

2019-04-29 18:39 UTC, luisjg commented on app/Http/Controllers/ModuleProgressController.php
> +use App\Jobs\SendNewModuleEmail;
I don't think this file was added to git

2019-05-23 23:54 UTC, liadGolan requested changes
The service test should test for failure and the email send should be updated

2019-05-23 23:54 UTC, liadGolan commented on app/Jobs/SendNewModuleEmail.php
> +        Mail::to((env('RECIEVE_EMAIL')))->send(new NewModuleAvailable($mail));
Should send to student email if on production ( one of the other mail senders has this for students )

2019-05-24 00:13 UTC, liadGolan approved these changes
👍

2019-05-24 17:31 UTC, luisjg approved these changes
👍

2019-05-24 17:31 UTC, merged